import os

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600

PLATFORM_WIDTH = 150
PLATFORM_HEIGHT = 20

PLATFORM1_X = 20
PLATFORM1_Y = 500

PLATFORM2_X = 100
PLATFORM2_Y = 400

PLATFORM3_X = 300
PLATFORM3_Y = 200

PLATFORM4_X = 500
PLATFORM4_Y = 500

PLATFORM_SPEED = 0

COIN_WIDTH = 30
COIN_HEIGHT = 30
COIN_SPEED = 0

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 80
PLAYER_SPEED = 2

GRAVITY_SPEED = 1

BLUE = (200, 255, 255)
BLACK = (0, 0, 0)

PROJECT_PATH = os.path.abspath(__file__ + "/..")
RESOURCES_PATH = os.path.join(PROJECT_PATH, "resources")

PLATFORM_IMAGE_PATH = os.path.join(RESOURCES_PATH, "platform.png")
COIN_IMAGE_PATH = os.path.join(RESOURCES_PATH, "coin.png")
PLAYER_IMAGE_PATH = os.path.join(RESOURCES_PATH, "player.png")

CAPTION = "Platformer"