import os


WINDOW_WIDTH = 880
WINDOW_HEIGHT = 600


DINO_X = 50
DINO_Y = WINDOW_HEIGHT - 40
DINO_WIDTH = 70
DINO_HEIGHT = 30
DINO_SPEED = 1
JUMP_ACC = 20
GRAVITY_SPEED = 10

BAT_X = WINDOW_WIDTH - 50
BAT_Y = WINDOW_HEIGHT - 50
BAT_WIDTH = 150
BAT_HEIGHT = 30

CACTUS_X = WINDOW_WIDTH - 50
CACTUS_Y = WINDOW_HEIGHT - 10
CACTUS_WIDTH = 30
CACTUS_HEIGHT = 30


OBSTACLE_SPEED = 5


BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

FONT_SIZE = 60

PROJECT_PATH = os.path.abspath(__file__ + "/..")
IMAGES_PATH = os.path.join(PROJECT_PATH, "images")

STAND_IMAGE_PATH = os.path.join(IMAGES_PATH, "stand.png")
CROUCH_IMAGE_PATH = os.path.join(IMAGES_PATH, "crouch.png")
BAT_IMAGE_PATH = os.path.join(IMAGES_PATH, "bat.png")
CACTUS_IMAGE_PATH = os.path.join(IMAGES_PATH, "cactus.png")

CAPTION = "Dino"
WIN_TEXT = "Перемога"
LOSE_TEXT =  "Поразка"

FPS = 60