# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Mark\Desktop\Logika_Python\notes\ui\MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.setWindowModality(QtCore.Qt.NonModal)
        MainScreen.resize(800, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MainScreen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 581))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mainRow = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mainRow.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mainRow.setContentsMargins(0, 0, 0, 0)
        self.mainRow.setObjectName("mainRow")
        self.noteTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.noteTextEdit.setObjectName("noteTextEdit")
        self.mainRow.addWidget(self.noteTextEdit)
        self.rightColumn = QtWidgets.QVBoxLayout()
        self.rightColumn.setObjectName("rightColumn")
        self.notesLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.notesLabel.setObjectName("notesLabel")
        self.rightColumn.addWidget(self.notesLabel)
        self.notesListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.notesListWidget.setObjectName("notesListWidget")
        self.rightColumn.addWidget(self.notesListWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.createNoteBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.createNoteBtn.setObjectName("createNoteBtn")
        self.horizontalLayout_2.addWidget(self.createNoteBtn)
        self.deleteNoteBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteNoteBtn.setObjectName("deleteNoteBtn")
        self.horizontalLayout_2.addWidget(self.deleteNoteBtn)
        self.rightColumn.addLayout(self.horizontalLayout_2)
        self.saveNoteBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveNoteBtn.setObjectName("saveNoteBtn")
        self.rightColumn.addWidget(self.saveNoteBtn)
        self.tagsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.tagsLabel.setObjectName("tagsLabel")
        self.rightColumn.addWidget(self.tagsLabel)
        self.tagsListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.tagsListWidget.setObjectName("tagsListWidget")
        self.rightColumn.addWidget(self.tagsListWidget)
        self.searchLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.rightColumn.addWidget(self.searchLineEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addTagBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addTagBtn.setObjectName("addTagBtn")
        self.horizontalLayout_3.addWidget(self.addTagBtn)
        self.deleteTagBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteTagBtn.setObjectName("deleteTagBtn")
        self.horizontalLayout_3.addWidget(self.deleteTagBtn)
        self.rightColumn.addLayout(self.horizontalLayout_3)
        self.searchBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.searchBtn.setObjectName("searchBtn")
        self.rightColumn.addWidget(self.searchBtn)
        self.mainRow.addLayout(self.rightColumn)

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Розумні нотатки"))
        self.notesLabel.setText(_translate("MainScreen", "Список заміток"))
        self.createNoteBtn.setText(_translate("MainScreen", "Створити замітку"))
        self.deleteNoteBtn.setText(_translate("MainScreen", "Видалити замітку"))
        self.saveNoteBtn.setText(_translate("MainScreen", "Зберегти замітку"))
        self.tagsLabel.setText(_translate("MainScreen", "Список тегів"))
        self.addTagBtn.setText(_translate("MainScreen", "Додати тег"))
        self.deleteTagBtn.setText(_translate("MainScreen", "Видалити тег"))
        self.searchBtn.setText(_translate("MainScreen", "Шукати по тегу"))