# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Марк\Desktop\Logika_Python\notes\ui\xmlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 589)
        self.verticalLayoutWidget = QtWidgets.QWidget(mainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.notesTextColumn = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.notesTextColumn.setContentsMargins(0, 0, 0, 0)
        self.notesTextColumn.setObjectName("notesTextColumn")
        self.notesTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.notesTextEdit.setObjectName("notesTextEdit")
        self.notesTextColumn.addWidget(self.notesTextEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(mainWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(510, 10, 271, 571))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.buttonsColumn = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.buttonsColumn.setContentsMargins(0, 0, 0, 0)
        self.buttonsColumn.setObjectName("buttonsColumn")
        self.notesListLable = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.notesListLable.setObjectName("notesListLable")
        self.buttonsColumn.addWidget(self.notesListLable)
        self.notesListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesListWidget.sizePolicy().hasHeightForWidth())
        self.notesListWidget.setSizePolicy(sizePolicy)
        self.notesListWidget.setObjectName("notesListWidget")
        self.buttonsColumn.addWidget(self.notesListWidget)
        self.notesStateRow = QtWidgets.QHBoxLayout()
        self.notesStateRow.setSpacing(4)
        self.notesStateRow.setObjectName("notesStateRow")
        self.createNoteButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createNoteButton.sizePolicy().hasHeightForWidth())
        self.createNoteButton.setSizePolicy(sizePolicy)
        self.createNoteButton.setObjectName("createNoteButton")
        self.notesStateRow.addWidget(self.createNoteButton)
        self.deleteNoteButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteNoteButton.sizePolicy().hasHeightForWidth())
        self.deleteNoteButton.setSizePolicy(sizePolicy)
        self.deleteNoteButton.setObjectName("deleteNoteButton")
        self.notesStateRow.addWidget(self.deleteNoteButton)
        self.buttonsColumn.addLayout(self.notesStateRow)
        self.saveNoteButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.saveNoteButton.setObjectName("saveNoteButton")
        self.buttonsColumn.addWidget(self.saveNoteButton)
        self.tagsListLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.tagsListLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tagsListLabel.setObjectName("tagsListLabel")
        self.buttonsColumn.addWidget(self.tagsListLabel)
        self.tagsListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.tagsListWidget.setObjectName("tagsListWidget")
        self.buttonsColumn.addWidget(self.tagsListWidget)
        self.searchLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.searchLineEdit.setInputMask("")
        self.searchLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.buttonsColumn.addWidget(self.searchLineEdit)
        self.tagsStateRow = QtWidgets.QHBoxLayout()
        self.tagsStateRow.setObjectName("tagsStateRow")
        self.addTagButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.addTagButton.setObjectName("addTagButton")
        self.tagsStateRow.addWidget(self.addTagButton)
        self.deleteTagButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.deleteTagButton.setObjectName("deleteTagButton")
        self.tagsStateRow.addWidget(self.deleteTagButton)
        self.buttonsColumn.addLayout(self.tagsStateRow)
        self.tagSearchButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.tagSearchButton.setObjectName("tagSearchButton")
        self.buttonsColumn.addWidget(self.tagSearchButton)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Розумні нотатки"))
        self.notesListLable.setText(_translate("mainWindow", "Список заміток"))
        self.createNoteButton.setText(_translate("mainWindow", "Створити замітку"))
        self.deleteNoteButton.setText(_translate("mainWindow", "Видалити замітку"))
        self.saveNoteButton.setText(_translate("mainWindow", "Зберегти замітку"))
        self.tagsListLabel.setText(_translate("mainWindow", "Список тегів"))
        self.searchLineEdit.setPlaceholderText(_translate("mainWindow", "Введіть тег..."))
        self.addTagButton.setText(_translate("mainWindow", "Додати до замітки"))
        self.deleteTagButton.setText(_translate("mainWindow", "Видалити з замітки"))
        self.tagSearchButton.setText(_translate("mainWindow", "Шукати по тегу"))



app = QtWidgets.QApplication([])
mainWindow = QtWidgets.QWidget()
ui = Ui_mainWindow()
ui.setupUi(mainWindow)
