import os

WINDOW_WIDTH = 700
WINDOW_HEIGHT = 500
WINDOW_CAPTION = "Лабіринт"

# шлях до папки з проектом
PROJECT_PATH = os.path.abspath(__file__ + "/..")
# шлях до папки з ресурсами: зображення, звуки
RESOURCES_PATH = os.path.join(PROJECT_PATH, "resources")

BACKGROUND_PATH = os.path.join(RESOURCES_PATH, "background.jpg")
PLAYER_PATH = os.path.join(RESOURCES_PATH, "hero.png")
MONSTER_PATH = os.path.join(RESOURCES_PATH, "cyborg.png")
GOAL_PATH = os.path.join(RESOURCES_PATH, "treasure.png")

SPRITE_WIDTH = 65
SPRITE_HEIGHT = 65

PLAYER_X = 5
PLAYER_Y = WINDOW_HEIGHT - 80

MONSTER_X = 700
MONSTER_Y = 400

MONSTER_RIGHT_POINT = 470
MONSTER_LEFT_POINT = WINDOW_WIDTH - 85


GOAL_X = WINDOW_WIDTH - 120
GOAL_Y = WINDOW_HEIGHT - 80

PLAYER_SPEED = 4
MONSTER_SPEED = 2
GOAL_SPEED = 0

FPS = 60

WALL_COLOR1 = 154
WALL_COLOR2 = 205
WALL_COLOR3 = 50

WALL_X = 100

WALL1_Y = 20
WALL1_WIDTH = 450
WALL1_HEIGHT = 10

WALL2_Y = 480
WALL2_WIDTH = 350
WALL2_HEIGHT = 10

WALL3_Y = 20
WALL3_WIDTH = 10
WALL3_HEIGHT = 380

FONT_SIZE = 70

LOSE_TEXT = "ПРОГРАШ"
WIN_TEXT = "ПЕРЕМОГА"

BLACK = (0, 0, 0)