from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        mainWindow.resize(645, 456)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(mainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 151, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.photoListColumn = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.photoListColumn.setContentsMargins(0, 0, 0, 0)
        self.photoListColumn.setObjectName("photoListColumn")
        self.folderButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.folderButton.setObjectName("folderButton")
        self.photoListColumn.addWidget(self.folderButton)
        self.photoListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.photoListWidget.setObjectName("photoListWidget")
        self.photoListColumn.addWidget(self.photoListWidget)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(mainWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 10, 461, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.editorColumn = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.editorColumn.setContentsMargins(0, 0, 0, 0)
        self.editorColumn.setObjectName("editorColumn")
        self.photoLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photoLabel.sizePolicy().hasHeightForWidth())
        self.photoLabel.setSizePolicy(sizePolicy)
        self.photoLabel.setObjectName("photoLabel")
        self.editorColumn.addWidget(self.photoLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.leftButton.setObjectName("leftButton")
        self.horizontalLayout.addWidget(self.leftButton)
        self.rightButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.rightButton.setObjectName("rightButton")
        self.horizontalLayout.addWidget(self.rightButton)
        self.mirrorButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mirrorButton.setObjectName("mirrorButton")
        self.horizontalLayout.addWidget(self.mirrorButton)
        self.sharpnessButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sharpnessButton.setObjectName("sharpnessButton")
        self.horizontalLayout.addWidget(self.sharpnessButton)
        self.grayButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.grayButton.setObjectName("grayButton")
        self.horizontalLayout.addWidget(self.grayButton)
        self.editorColumn.addLayout(self.horizontalLayout)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "East Editor"))
        self.folderButton.setText(_translate("mainWindow", "Папка"))
        self.photoLabel.setText(_translate("mainWindow", "Картинка"))
        self.leftButton.setText(_translate("mainWindow", "Вліво"))
        self.rightButton.setText(_translate("mainWindow", "Вправо"))
        self.mirrorButton.setText(_translate("mainWindow", "Дзеркало"))
        self.sharpnessButton.setText(_translate("mainWindow", "Різкість"))
        self.grayButton.setText(_translate("mainWindow", "Ч/Б"))



app = QtWidgets.QApplication([])
mainWindow = QtWidgets.QWidget()
ui = Ui_mainWindow()
ui.setupUi(mainWindow)