#:kivy <ExampleScreenManager>:
    Screen:
        name: "first_screen"
        BoxLayout:
            orientation: "vertical"
            Label:
                text: "Інструкція"
            BoxLayout:
                Label:
                    text: "Введіть ім'я"
                TextInput:
                    multiline: False
            BoxLayout:
                Label:
                    text: "Введіть вік"
                TextInput:
                    multiline: False
            Button:
                text: "Почати"
    Screen:
    Screen:
    Screen:
    Screen:
