import os

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600

PLATFORM_WIDTH = 150
PLATFORM_HEIGHT = 20

PLATFORM4_WIDTH = 300
PLATFORM4_HEIGHT = 20

PLATFORM1_X = 20
PLATFORM1_Y = 500

PLATFORM2_X = 100
PLATFORM2_Y = 400

PLATFORM3_X = 300
PLATFORM3_Y = 300

PLATFORM4_X = 400
PLATFORM4_Y = 500

PLATFORM5_X = 800
PLATFORM5_Y = 500



PLATFORM_SPEED = 0

COIN_WIDTH = 30
COIN_HEIGHT = 30
COIN_SPEED = 0

ENEMY_WIDTH = 60
ENEMY_HEIGHT = 60
ENEMY_SPEED = 0

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 80
PLAYER_SPEED = 10

PLAYER_X =  PLATFORM1_X + PLATFORM_WIDTH / 2 - PLAYER_WIDTH
PLAYER_Y =  PLATFORM1_Y - PLAYER_HEIGHT

ENEMY_X =  PLATFORM4_X + PLATFORM_WIDTH / 2 + ENEMY_WIDTH
ENEMY_Y = PLATFORM4_Y - ENEMY_HEIGHT

COIN1_X =  PLATFORM3_X + PLATFORM_WIDTH / 2 - COIN_WIDTH
COIN1_Y =  PLATFORM3_Y - COIN_HEIGHT

COIN2_X =  PLATFORM4_X + PLATFORM_WIDTH / 2 - COIN_WIDTH
COIN2_Y =  PLATFORM4_Y - COIN_HEIGHT

COIN3_X =  PLATFORM5_X + PLATFORM_WIDTH / 2 - COIN_WIDTH
COIN3_Y =  PLATFORM5_Y - COIN_HEIGHT

GRAVITY_SPEED = 10

BLUE = (200, 255, 255)
BLACK = (0, 0, 0)

PROJECT_PATH = os.path.abspath(__file__ + "/..")
RESOURCES_PATH = os.path.join(PROJECT_PATH, "resources")

PLATFORM_IMAGE_PATH = os.path.join(RESOURCES_PATH, "platform.png")
COIN_IMAGE_PATH = os.path.join(RESOURCES_PATH, "coin.png")
PLAYER_IMAGE_PATH = os.path.join(RESOURCES_PATH, "player.png")
ENEMY_IMAGE_PATH = os.path.join(RESOURCES_PATH, "enemy.png")

CAPTION = "Platformer"

FPS = 60

WIN_TEXT = "Перемога"
LOSE_TEXT = "Поразка"
