
TITLE = "Memo Card"

QUESTION_SCREEN_WIDTH = 600
QUESTION_SCREEN_HEIGHT = 500

EDIT_SCREEN_WIDTH = 600
EDIT_SCREEN_HEIGHT = 500

START_QUESTION = "Яблуко"

START_ANS1 = "apple"
START_ANS2 = "building"
START_ANS3 = "caterpillar"
START_ANS4 = "application"


MENU_BUTTON_TEXT = "Меню"
REST_BUTTON_TEXT = "Відпочити"
ANSWER_BUTTON_TEXT = "Відповісти"

MINUTES_TEXT = "хвилин"

QUESTION_GROUP_BOX_TEXT = "Варіанти відповідей"
RESULT_GROUP_BOX_TEXT = "Результати"

START_MINUTES = 30