#:kivy!
#:import from_hex kivy.utils.get_color_from_hex
#:import colormap kivy.utils.colormap


#:set main_color "#F3AF12"
#:set main_color_dark "#F37C12"

<MenuButton@Button>:
    size_hint: 1, 0.15
    font_size: "20sp"
    background_normal: ""
    background_color: from_hex(main_color)
    color: 0, 0, 0, 1
    on_press:
        self.background_color = from_hex(main_color_dark)
    on_release:
        self.background_color = from_hex(main_color)


<MenuScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "20dp"

        canvas.before:
            Color:
                rgba: colormap["blue"]

            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: "assets/images/title.png"
            size_hint: 1, 0.5

        Label:
            text: "Main Menu"
            font_size: "40sp"
            size_hint: 1, 0.2

        MenuButton:
            text: "PLAY"
            on_press: root.go_game()

        MenuButton:
            text: "SETTINGS"
            on_press: root.go_settings()

        MenuButton:
            text: "EXIT"
            on_press: root.exit_app()